### ISSUE TITLE
Question: What happens if the merge fails?

### ISSUE THREAD

**Issue by MexHigh** [danger89/repo_pull_sync_docker_image#1]
First of all, thank your for this idea. I'm using your `gitlab-ci.yml` in my own Gitlab :)

But what happens if the merge fails (e.g. when the upstream edited the same file as me in a different way)? Usually, an editor would be opened to resolve the conflicts which is not possible in a CI job. Would the job just fail without pushing it? This would be good, as I would receive an email then to resolve it manually.

Or might rebasing be a more suitable approach?

**Comment by melroy89** [comment]
Good question. The pipeline will just fail. Because the git merge command exists with non zero exit code.

That is the standard working on gitlab pipeline. 

That being said, I may want to change my code to use git rebase over git merge. But that's another topic.

**Comment by MexHigh** [comment]
Ok thank you 👍

**Comment by melroy89** [comment]
Code is updated to use `rebase`. Which will result into a better git history. 

I also updated the README regarding pipeline failure.
